Update type_with_alignment.hpp
boostorg/type_traits pull request #145
Opened 2020-09-09 18:12 UTC by tobias-loew

Replaced dead link
I couldn't find the original link ( even not with a web time machine)
Could someone please check, if the new link points to the correct location?
Thanks

2020-09-09 19:03 UTC, glenfe requested changes

2020-09-09 19:03 UTC, glenfe commented on include/boost/type_traits/type_with_alignment.hpp
> +// see https://groups.google.com/g/boost-developers-archive/c/cM9xfiqkwLo
The better link is: https://lists.boost.org/Archives/boost/2014/03/212391.php (No need to retain the "originally" part).

2020-09-10 06:40 UTC, tobias-loew commented
I've updated the link.
Thanks for the hint.

2020-09-10 13:27 UTC, glenfe approved these changes

2021-03-07 11:47 UTC, merged